setwd("~/Work/Professional development/Data Science course/Exploratory Data Analysis")
library(data.table)
file <- fread("household_power_consumption.txt", na.strings="?")
date_time <- strptime(paste(file[,Date], file[,Time], sep = " "), format = "%d/%m/%Y %H:%M:%S")
file$date_time <- as.POSIXct(date_time)
data <-subset(file, date_time >= as.POSIXct ('2007-02-01') & date_time < as.POSIXct ('2007-02-03'))
data <- data[,weekdays:= weekdays(date_time, abbreviate = TRUE)]
par(mfcol = c(2,2))
plot(data[,Global_active_power], type = "l", xlab = "", xaxt = "n", ylab = "Global Active Power")
Thu <- data[, weekdays == "Thu"]
sum(Thu)
nrow(data)
v1 <- c(0, 1441, 2881)
v2 <- c("Thu", "Fri", "Sat")
axis (side = 1, at = v1, labels = v2)
plot(data[,Sub_metering_1], type = "n", xlab = "", xaxt = "n", ylab = "Energy sub metering")
points(data[,Sub_metering_1], type = "l", col = "black")
points(data[,Sub_metering_2], type = "l", col = "red")
points(data[,Sub_metering_3], type = "l" , col = "blue")
axis (side = 1, at = v1, labels = v2)
legend("topright", legend = c("Energy_sub_metering_1","Energy_sub_metering_2","Energy_sub_metering_3"), lty = 1, col = c("black", "red", "blue"), cex = 0.6)
plot(data[,Voltage], type = "l", xlab = "dateline", xaxt = "n", ylab = "Voltage")
axis (side = 1, at = v1, labels = v2)
plot(data[,Global_reactive_power], type = "l", xlab = "dateline", xaxt = "n", ylab = "Global_reactive_power")
axis (side = 1, at = v1, labels = v2)
dev.copy (png, file = "plot4.png")
dev.off()